from __future__ import annotations

import os
import subprocess
import uuid


def _listing_block(title: str, description: str, body: str) -> str:
    """Render a section whose body is shown verbatim via `listings`.

    `lstlisting` reads its content verbatim, so arbitrary source code or program
    output (with `$`, `_`, `\\`, `{`, `}`, …) is embedded safely without escaping.
    """
    return (
        f"\\section*{{{title}}}\n"
        f"{description}\n\n"
        "\\begin{lstlisting}\n"
        f"{body.rstrip()}\n"
        "\\end{lstlisting}\n"
    )


def generate_pdf_report(
    conjecture: str,
    code: str | None = None,
    execution_result: dict | None = None,
    workspace_dir: str = "workspace/reports",
) -> str:
    """Compile a formal PDF report for a validated theorem.

    Besides the validated hypothesis, the report now embeds the Oracle's
    validation script (``code``) and its execution result (``execution_result``)
    when provided, so the PDF is a self-contained audit artifact. Both extra
    arguments are optional; omitting them reproduces the original conjecture-only
    report, so existing callers keep working.
    """
    os.makedirs(workspace_dir, exist_ok=True)

    filename_base = f"theorem_report_{uuid.uuid4().hex[:8]}"
    tex_filepath = os.path.join(workspace_dir, f"{filename_base}.tex")

    # ── Optional Oracle sections ─────────────────────────────────────────
    code_section = ""
    if code and str(code).strip():
        code_section = _listing_block(
            "Oracle Validation Script",
            "Python generated by the Translator agent and executed by the Oracle "
            "to verify the hypothesis:",
            str(code),
        )

    result_section = ""
    if execution_result:
        exit_code = execution_result.get("exit_code", "n/a")
        engine = execution_result.get("engine", "python")
        stdout = str(execution_result.get("stdout", "")).strip()
        stderr = str(execution_result.get("stderr", "")).strip()
        body = f"exit_code: {exit_code}\nengine: {engine}\n"
        if stdout:
            body += f"\nSTDOUT:\n{stdout}\n"
        if stderr:
            body += f"\nSTDERR:\n{stderr}\n"
        result_section = _listing_block(
            "Oracle Execution Result",
            "Captured output of the validation run:",
            body,
        )

    latex_content = f"""\\documentclass[11pt, a4paper]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{amsmath, amssymb, amsthm}}
\\usepackage{{geometry}}
\\usepackage{{listings}}
\\usepackage{{xcolor}}
\\geometry{{margin=2cm}}

\\lstset{{
  basicstyle=\\ttfamily\\small,
  breaklines=true,
  breakatwhitespace=false,
  columns=fullflexible,
  keepspaces=true,
  showstringspaces=false,
  frame=single,
  rulecolor=\\color{{gray!45}},
  aboveskip=0.7em,
  belowskip=0.7em,
}}

\\title{{\\textbf{{ASTRA Theorem Validation Report}}}}
\\author{{ASTRA Production Orchestrator}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle

\\section*{{Validated Hypothesis}}

{conjecture}

{code_section}
{result_section}
\\vspace{{1.5cm}}
\\hrule
\\vspace{{0.5cm}}
\\noindent \\small \\textit{{This theorem was autonomously generated, translated, and mathematically verified by the ASTRA zero-trust engine.}}

\\end{{document}}
"""
    with open(tex_filepath, "w", encoding="utf-8") as f:
        f.write(latex_content)

    # Compile
    subprocess.run(["pdflatex", "-interaction=nonstopmode", f"{filename_base}.tex"], cwd=workspace_dir, capture_output=True)

    pdf_path = os.path.join(workspace_dir, f"{filename_base}.pdf")
    if not os.path.exists(pdf_path):
        raise RuntimeError(f"pdflatex ran but did not produce {pdf_path}")
    return pdf_path
